[package]
name = "rsfractal"
version = "0.1.0"
authors = ["Ville Orkas <ville@orkas.fi>"]
edition = "2018"

[dependencies]
num-complex = "*"
num-traits = "*"
serde = { version = "*", features = ["derive"] }

[target.wasm32-unknown-unknown.dependencies]
seed = "*"
wasm-bindgen = "*"
web-sys = { version = "*", features = ["DomRect", "DomRectReadOnly"] }

[dev-dependencies]
image = "*"
rayon = "*"
serde_json = "*"

[lib]
crate-type = ["rlib", "cdylib"]

[[example]]
name = "main"

[profile.release]
lto = true
opt-level = 3
panic = "abort"