[package]
name = "rsfractal"
version = "0.1.0"
authors = ["Ville Orkas <ville@orkas.fi>"]
edition = "2018"

[dependencies]
num = "*"
num-complex = "*"
num-traits = "*"
image = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
futures-preview = { version = "=0.3.0-alpha.16", features = ["async-await", "nightly"] }

[profile.release]
lto = true
opt-level = 3
debug = true
