[package]
name = "rsfractal"
version = "0.1.0"
authors = ["Ville Orkas <ville@orkas.fi>"]
edition = "2018"

[dependencies]
num = "*"
num-complex = "*"
num-traits = "*"
serde = { version = "*", features = ["derive"] }

[dev-dependencies]
image = "*"
rayon = "*"
serde_json = "*"
criterion = "*"

[lib]
bench = false

[[example]]
name = "main"

[[bench]]
name = "main"
harness = false

[profile.release]
lto = true
opt-level = 3
debug = true
panic = "abort"