[build]
target = "index.html"
filehash = false
minify = "on_release"

[tools]
tailwindcss = "4.0.11"

[watch]
watch = ["../mandelbrot"]

[serve.headers]
"Cross-Origin-Opener-Policy" = "same-origin"
"Cross-Origin-Embedder-Policy" = "require-corp"

[[hooks]]
stage = "post_build"
command = "scripts/postprocess.sh"
