[build]
rustc-wrapper = "sccache"

[target.'cfg(not(target_arch = "wasm32"))']
rustflags = "-C target-cpu=native"

[target.wasm32-unknown-unknown]
rustflags = """-C target-feature=\
    +atomics,\
    +bulk-memory,\
    +exception-handling,\
    +extended-const,\
    +multivalue,\
    +mutable-globals,\
    +nontrapping-fptoint,\
    +reference-types,\
    +relaxed-simd,\
    +sign-ext,\
    +simd128,\
    +tail-call,\
    +bulk-memory-opt,\
    +call-indirect-overlong,\
    +fp16,\
    +multimemory
"""

[unstable]
build-std = ["panic_abort", "std"]
